# Generated by Django 2.2.5 on 2020-08-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Quotes',
        ),
    ]
