# Generated by Django 2.2.5 on 2020-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_quotes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
